# Generated by Django 3.0.7 on 2020-07-05 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20200705_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='player_name',
        ),
    ]
