# Generated by Django 3.0.7 on 2020-07-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20200705_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
