# Generated by Django 3.0.7 on 2020-07-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20200708_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
