# Generated by Django 3.0.7 on 2020-07-09 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20200708_2104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='number',
            new_name='search_number',
        ),
    ]
