# Generated by Django 3.0.7 on 2020-07-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20200709_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergameinfo',
            name='try_counts',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
